### ISSUE TITLE
The ">" type naming

### ISSUE THREAD

**Issue by ploddi** [getkyo/kyo#142]
Could you please explain the reasoning behind `>` type naming? How do you pronounce it?

```scala
// Expect an 'Int' after handling 
// the 'Options' effect
Int > Options
```

I did not quite get the logic behind it. `Int` "goes" into `Options` context? `>` dictates some notion of "direction" naturally. Why is it not other way around for example? `Int < Options` (expect a Int after Options?)

Do you consider sticking to `?` context abstractions theme? Something like `Int :? Options`

**Comment by fwbrasil** [comment]
We discussed this on discord and I liked the suggestion of calling it the "pending" type. It works quite well when reading type signatures! I don't see a need to find a symbol that conveys meaning, it's more about syntax. The suggestion of using `<` sounds reasonable, though. 

I've [opened a PR](https://github.com/getkyo/kyo/pull/143) introducing the "pending" name but I'll keep the issue open to hear other ideas as well.

**Comment by johnhungerford** [comment]
I agree with the recommendation to use `<` instead of `>`.

`T < Effects` indicates that the value `T` is deriving from `Effects` rather than the other way around, and even reflects the binding of a `flatMap`ed value to a parameter within a for comprehension:

```scala
val result: T < Effects = for {
  t <- effect
} yield t
```

I also agree calling it "T pending Effects" is a good term.

**Comment by sideeffffect** [comment]
Please excuse a random comment from the peanut gallery, but there is also `@` which is commonly used for annotations, so it also might be a good candidate. People will typically visually see `T @ Effects` as `T` with some `Effects`, bound together via the `@`. On the other hand, `<` doesn't visually bind `T` and `Effects` together, so users probably won't intuitively see `T < Effects` as belonging together, but as `T` and `Effects` not having anything with each other, especially if the types get larger.

**Comment by regiskuckaertz** [comment]
Flix uses `a \ eff`
Unison uses `{eff} a`
Koka uses `<eff> a`

**Comment by ploddi** [comment]
Scala 3 context functions use `?=>` syntax, so it also could be used as theme. `A :? Effects` and I mentioned in original post has some "context bound" flavor.

**Comment by johnhungerford** [comment]
It makes sense to stick to one character, as types are going to be verbose and the fewer characters the better. My own preference is still `T < S`, as it indicates the `T` is coming from `S`, but @sideeffffect 's suggestion to use `@` also makes sense to me.

**Comment by yawaramin** [comment]
How about `!`? `!` is used sometimes to indicate an effect e.g. in F# computation expressions. E.g. `val x: Int ! Options = ...`

**Comment by diesalbla** [comment]
> How about !? ! is used sometimes to indicate an effect e.g. in F# computation expressions. E.g. val x: Int ! Options = ...

That would be easier if the exclamation mark `!` had not been used by Akka, one of the major Scala libraries, as the primitive for sending messages across actors.

**Comment by diesalbla** [comment]
So, one intuition I have sometimes heard about "algebraic effects" is that, if one sees programs as functions and computers as evaluators, an "effect" is some action, raised by the evaluation of the program, that the interpreter delegates on other system to do. Following that intuition, one can use ASCII art to paint effects as "interpreter components" that need to be plugged: `|-*`.

Another idea can be the Prolog rule operator: `:-`, so that `e: T :-* F` indicates that evaluation of expression `e` can return a value of type T if the effects `F` are handled.

One inconvenience is that in an English U.S. keyboard layout that may require `Shift ;` `-` `Shift *` which can be tiring. In general it is worth checking the ergonomics of these operators. A simpler operator like `@|` only requires `Shift 2 \`.

**Comment by fwbrasil** [comment]
Thanks for the suggestions, folks! I think I wouldn't be open to multi-character symbols since it'd increase the visual cluttering. I'm with @johnhungerford so far and think that `<` works well. The `@` also sounds like a good option but I wonder if we'd have issues with Scala treating it differently since it's a symbol used by annotations and bind params in pattern matching.

**Comment by yawaramin** [comment]
@diesalbla I don't think Akka's use of `!` is a big concern, after all if we are concerned with other uses then it makes it difficult to use `<`/`>` (because math) or `@` (because annotation symbol). Besides, it's extremely unlikely that people are using Akka and Kyo together :-)

**Comment by lbialy** [comment]
Late to the party but just wanted to add that I thought it should be `<` as well since viewing the slides from the talk. I read it as `A out of X, Y and Z` which are required to obtain it.

**Comment by fwbrasil** [comment]
Okay folks, it’s best to make this decision soon since we’re going to have to deal with code conflicts. I’m planning to merge https://github.com/getkyo/kyo/pull/150 tomorrow EOD. Please leave a 👍🏼 or 👎🏼 and let me know if there are any major concerns. Thanks!!

**Comment by fwbrasil** [comment]
I've finally made the change to `<`. Thanks for all the input, folks! https://github.com/getkyo/kyo/commit/73ac1e2f062d2a7ddd661accb1edecf526cd80e0

**Comment by fwbrasil** [comment]
hey @regiskuckaertz! Yeah, it'd be nice to avoid parenthesis when there are multiple effects but I think changing the symbol wouldn't fix that? It's something that might need to be improved in the compiler by making `&` have precedence, which seems a reasonable behavior.

**Comment by regiskuckaertz** [comment]
Yes it would! [Operator precedence](https://docs.scala-lang.org/tour/operators.html) also works at the type level (it must, otherwise working with `compiletime.ops` would be a headache). But I made a mistake, `\` has higher precedence than `&`. But `^` doesn't! Hmm that's probably why they picked it, since `|` is already taken for union types. So this would work:
```scala
infix type ^[A, B]
def foo(f: A ^ X & Y & Z): A = ???
def bar: A ^ (X & Y & Z) = ??? // wrapping unnecessary, here just to prove it compiles
def baz: A ^ X & Y & Z = ???
def qux = foo(bar)
def quux = foo(baz)
```
Gaah, I wish I had thought of that sooner. Sometimes you have to wonder how it is that Scala is such a complex language and yet somehow letting people define operator precedence it's a bridge too far.
