### ISSUE TITLE
Unified API for effects with extension methods

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#145]
The current design of kyo keeps effect types segregated, so that a separate import is required for each one, and each has a separate API.

```scala
import kyo.options.*
import kyo.ios.*
import kyo.fibers.*

val optEffect = Options.get(Some("hello world"))
val ioEffect = IOs(println("hell world"))
val forkedEffect = Fibers.init(ioEffect)

val handledOpt = Options.run(optEffect)
val handledIo = IOs.run(ioEffect)
val handledFiber = IOs.run(Fibers.run(forkedEffect))
```

It would be much easier for the developer to use a single export for core effects, and have extension methods on `T < Fs` to more easily handle effects. I'm obviously thinking of the ZIO API here:

```scala
import kyo.*

val optEffect = KYO.fromOption(Some("hello world"))
val ioEffect = KYO.attempt(println("hello world")
val forkedEffect = ioEffect.fork

val handledOpt = optEffect.runOptions
val handledIo = ioEffect.runIO
val handledFiber = forkedEffect.join
```

**Comment by fwbrasil** [comment]
I think moving effects to extension methods of `>` would hurt usability given that users would have to browse over several methods to encounter the ones related to the effects they need to use. Calling effect methods explicitly doesn't introduce much syntax overhead and makes code more friendly to newcomers IMO.

I agree that'd be nice to avoid having to import each of the effects, though. I used to have a `kyo.all` object that would export all core effects but I removed it once I introduced Scala 2 support. Kyo also has multiple modules now, which complicates things a bit. Maybe we could have a `kyo-all` artifact that depends on all other modules and exports all effects?

**Comment by johnhungerford** [comment]
From what I can see, everything that I would want to be in the unified export is in the `core` module (`Aborts`, `Envs`, `Options`, `IOs`, `Fibers`), so I'm doubtful another module would be necessary, at least for my own needs.

One more plug for using extensions methods: 
1. using static functions on objects like `Options`, `Aborts`, etc, requires "back-tracking." You come up with an expression, and then you have to return to the beginning of the expression to then handle those effects, rather than calling a method at the end of the expression at the end, which is where you were when you thought of it:

```scala
val effect = Consoles
    .readLine
    .map(line => Tries.catching(v.toInt)
    .map(int => Options.get(Try(23 / int).toOption))
    // At this point I realize I want to handle `Tries` and `Options` to just get an `Option[Double]`
    // but now I have to go back to the top and wrap this all in an `Options.run { }`
    // I'd like just call something like:
    .triesToOptions
    .runOptions
```

2. You end up with super nested function calls that make it harder to follow what's happening
```scala
// Simple dependency
final case class Dep(int: Int)

val effect = for {
    int1 <- Envs[Dep].get.map(_.int)
    int2 <- Options.get(Some(23))
    int3 <- Aborts[String].get(Right(50))
    _ <- Consoles.println((int1 + int2 + int3).toString)
} yield ()

// To handle I have a super-nested expression:
Envs[Dep].run(Dep(900)(Options.run(Aborts[String].run(effect)))

// It would be much cleaner to be able run them in order
effect
    .runAborts[String]
    .runOptions
    .runEnvs[Dep](Dep(900))
```

At any rate, as I've started playing with this, I very quickly came up with a bunch of extension methods to use to make it less cumbersome managing the different effect types.

**Comment by fwbrasil** [comment]
How do you feel about this issue after some more contact with Kyo? I agree that extension methods would make Kyo's API more fluent for advanced users but I worry if it could make it more difficult to onboard newcomers since it tends to produce more terse code. The way Kyo's effects are structured should also facilitate learning since it's possible to teach each effect in isolation and people might have an easier time to form a mental model of which effects they should use for each task.

**Comment by johnhungerford** [comment]
I've been think about this. I still strongly feel that I would prefer a fluent zio-like API. Whenever I've done experiments with kyo, I've ended up just rolling my own API for convenience. I certainly wouldn't try to build a proper application without one. That said, I do understand your concern about onboarding -- you may be right that it's easier to get your head around.

I've been toying with the idea of making a separate "zikyo" library that just puts a ZIO facade on kyo. It would have a single `KYO` object with a bunch of factory methods as close to the ZIO ones as possible (but far fewer, it turns out, owing to kyo's design), and then provide a bunch of extension methods mimicking the methods on a `ZIO[R, E, A]`. (This is basically what I've already been using locally.) If you are interested, I could make it a separate, optional module in within kyo. However, the added complexity of having multiple ways of doing this could create an obstacle to adoption.

**Comment by fwbrasil** [comment]
Yeah, I think this tension between designing a library for both newcomers and advanced users is one of the main challenges of the project. Looking at your examples, maybe we could have a single generic method to enable the fluent use? It might a good compromise.

```scala
// Simple dependency
final case class Dep(int: Int)

val effect = for {
    int1 <- Envs[Dep].get.map(_.int)
    int2 <- Options.get(Some(23))
    int3 <- Aborts[String].get(Right(50))
    _ <- Consoles.println((int1 + int2 + int3).toString)
} yield ()

// new pipe method?
effect
    .pipe(Aborts[String].run)
    .pipe(Options.run)
    .pipe(Envs.run(Dep(900)))
```

**Comment by fwbrasil** [comment]
Regarding a ZIO-like facade, I think it might make sense to facilitate learning and adoption. I'd be open to having it as a separate repo under getkyo.

**Comment by johnhungerford** [comment]
I think a pipe method would be even more confusing to a new-comer than the combinators I had in mind, although at least would not clutter the namespace. But I'm pretty sure `pipe` can be imported from the standard library anyways.

I'll push my own code in a repo in my namespace and let you consider whether you want it under `getkyo`.

**Comment by fwbrasil** [comment]
Cool! Makes sense, if you prefer to keep it separate it’s fine with me as well. I’m looking forward to seeing it! Hopefully we can find some ways to bridge the gap between advanced users and newcomers :)

**Comment by fwbrasil** [comment]
Something I wanted to encourage you to do is to think of the ideal API rather than the one that fits with Kyo's current core. Making major changes to the library is still feasible at the current phase of the project, and in the end, I think this is more about syntax than how effects are organized, which is my main concern. The recent discussion with Kit on https://github.com/getkyo/kyo/issues/201 is a good example of how to experiment with Kyo's core. I'd be glad to help!

**Comment by kitlangton** [comment]
In general, I do find the ergonomics of methods defined upon an instance to be preferable to "free functions," a.k.a methods defined on a companion object. For me, the companion object is the ideal place for constructors, or perhaps _n > 2 arity_ methods—`ZIO.collectAll` for instance. (_This one of the reasons why I don't think I could go back to ML style languages._)

There's definitely a tradeoff; especially with a library like Kyo, where we don't have a single, unified Effect type to serve as the logical home for these methods. Instead, we would need to define extension methods. Though, we could have these all defined in one file, in order to regain some of that discoverability through source-spelunking. Additionally, I believe **autocomplete** is probably the most powerful factor in the discoverability and ergonomics of a library. 

When you have free functions spread across multiple companion objects, the user might have a difficult time figuring out what options are even available to them. Conversely, with extension methods, the user could simply type out `myKyo.` and have their IDE present all _relevant_* possibilities.

(*With extension methods, we could ensure that only the _relevant_ methods appear in autocomplete. For instance, if your Kyo does not depend on the Aborts effect, then autocomplete wouldn't be polluted with Aborts-specific, error handling methods. Libraries tend to not do this, but I think it could be worth experimenting with.)

It could be quite nice to call `catchAll/catchSome` _on_ a `Kyo` directly to handle an `Aborts`. In fact, I explored that a bit, and found a way to successfully infer the new set of effects, subtracting the `Aborts[E]`.

**Comment by johnhungerford** [comment]
@kitlangton  good idea. Here is a gist with the API I've been using locally. Scroll to the bottom to see a simple demo: https://gist.github.com/johnhungerford/8430b93fb2eebf4de40ab0808eee010e

Keep in mind I just sort of threw this together quickly and haven't tested most of the options. I also can't get it to compile with scala-cli, but it runs in my local sbt project.

@fwbrasil I'll keep your recommendation in line

**Comment by fwbrasil** [comment]
Sorry for the delay to reply here. I've been thinking about this and it's still not clear to me what a good direction could be. My main concern is keeping Kyo's design philosophy of having simple and isolated effects with a small set of canonical APIs.

I'd say that's an important departure from ZIO's approach, which focuses more on high-leverage combinators. Combinators are great for advanced users but significantly increase the API surface, making onboarding new users more challenging. Kyo's current API surface seems significantly smaller than ZIO's while still covering a large portion of its functionality.

Another important aspect is the direct syntax experience. Since the goal is to compose computations without a monadic API, providing statically-accessible APIs is a necessity, and operators we add to `<` might not even be [available in the direct syntax](https://github.com/getkyo/kyo/issues/211).

That said, I think Kyo ideally should position itself as a solution to bridge the gap between newcomers and advanced FP users. Maybe we could have separate interoperable APIs with different levels of complexity? We could still keep the same organization of effects but presented in different ways:

1. Direct syntax: This is what I'd expect the majority of Kyo's users to use.
2. Simplified monadic: Using the current monadic APIs + isolated effects.
3. Rich combinators: A ZIO-like user experience.

I'd be okay with the "rich combinators" API being in a separate project but we could also keep it in Kyo proper to facilitate maintenance. In case we see newcomers don't need to fall back to the "simplified monadic" APIs too often, we might even be able to eventually remove it (but somehow keeping the direct syntax experience and Kyo's design philosophy). I think if we're able to provide a seamless experience that allows advanced users to provide solutions newcomers can easily leverage in the direct syntax, it can become avenue for the evolution of functional programming in a way that has the chance to become a mainstream paradigm.

Regarding autocomplete, I'm not sure it's a very relevant concern. Going forward, the kind of autocomplete that matters the most is the one produced by AI copilots. Kyo's current organization of effects is great for example to put in a LLM system prompt since it's relatively compact. The clear separation of concerns in effects should also hep direct the LLM's reasoning and attention better.

**Comment by nightscape** [comment]
Regarding auto-completion vs. LLM: LLMs already today can [limit their output to grammars specified in BNF](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md). I think it is a logical next step to limit or refine the output according to completions provided by e.g. LSP. Otherwise the model would have to be fine-tuned every time the API changes or it would need to do constant RAG documentation lookups.
I think auto-completion would help both humans and in the near future also LLMs.

**Comment by fwbrasil** [comment]
@nightscape that's a good point! Constraining the output to a grammar can be quite useful but I believe there aren't any major providers with this feature yet. I think both Kyo's current APIs and a combinator-focused approach could be expressed as a grammar, though.

**Comment by fwbrasil** [comment]
@johnhungerford I think we can close this issue now that the work is continuing in https://github.com/getkyo/zikyo?

**Comment by johnhungerford** [comment]
Sounds good!
