### ISSUE TITLE
Make Java 21 optional

### ISSUE THREAD

**Issue by megri** [getkyo/kyo#199]
It seems like the build artefacts depend on JDK 21 since at least a few versions now. If this is intended it would be nice to mention it in the docs somewhere :)

**Comment by coleea** [comment]
according to https://github.com/getkyo/kyo/blob/b521227e09c2afcad4c4c43ab2734411bde3ddb2/kyo-core/jvm/src/main/scala/kyo/scheduler/Scheduler.scala#L41 , this project use Project Loom that requires JDK 21 version. So I think that It is intended to use JDK 21 Version.

**Comment by fwbrasil** [comment]
Sorry for the delay to reply. Yeah, it was intended but I'm starting to regret the decision. For example, Kyo isn't working on Scastie anymore because it doesn't support Java 21 bytecode. It's probably something that could get fixed but I worry users can end up hitting this kind of limitation too often.

I've renamed this issue to "Make Java 21 optional". In case anyone would like to pick this up, I think these are the necessary changes:

1. Move the code in `Scheduler.exec` to a new class `LoomSupport`: https://github.com/getkyo/kyo/blob/main/kyo-core/jvm/src/main/scala/kyo/scheduler/Scheduler.scala#L27
2. Avoid the direct use of Java 21 by calling methods via reflection (`Thread.ofVirtual` and `Executors.newThreadPerTaskExecutor`)
3. Keep the same virtualization flag and fall back to the regular cached thread pool in case the reflection is not accessible because the `--add-opens` isn't set.
4. Remove the Java 21 check from the sbt build: https://github.com/getkyo/kyo/blob/main/build.sbt#L260
5. Change the github workflows to use Java 11: https://github.com/getkyo/kyo/tree/main/.github/workflows

**Comment by 987Nabil** [comment]
@fwbrasil are you sure about this? I don't think kyo is what ppl will take for their legacy projects. And in my experience java updates (for services) are usually not a big deal. I think Scastie might be the outlier here.
Is it worth the effort and tradeoffs it brings?

But if you would continue, I'd recommend Java 17 and not 11 since it is the latest non loom LTS version.

**Comment by fwbrasil** [comment]
I think making it optional is a good tradeoff, especially in this initial phase of the project. I'm planning to explore a ZIO integration based on thread blocking, which was the main reason for the requirement. Even if that's the case, the solution should still work with regular thread blocking and virtualizing Kyo's workers can be an additional config users need to do for performance. Another common scenario would be the use of libraries that rely on thread blocking like JDBC, which would still work with regular thread blocking and virtualization could also be enabled to improve the performance.

Something that is an important downside for me is not gaining access to new APIs that are being introduced like MemorySegment for off-heap access but we still don't have anything in the codebase using them besides the Loom integration. I imagine we'd eventually make Java 21 required again if we see good opportunities to leverage new Java APIs.
