### ISSUE TITLE
New Encoding Again—Maybe

### ISSUE THREAD

**Issue by kitlangton** [getkyo/kyo#462]
As I was falling asleep last night, my mind wandered again—oh, the curse of programming—to implementing algebraic effect systems. When I worked on my little talk, I had a few extemporaneous practice sessions with my wife. I was trying to see just how incrementally I could make the refactoring from a basic free monad to a fully-powered, ad hoc effect handler implementation.

One eventually gets to the point where a generic `Command/Operation` has been extracted, and the handle loop must decide if it `accepts` it or not. This leads to the bit which I had the most trouble decomposing pedagogically: The necessity of the continuation which *continues* the current handler loop *only after* some other, heretofore unknown, handler clears the *unaccepted* operation blocking the path ahead. This step introduces a great deal of complexity all at once (I actually never even reached this stage in my final talk 😅—due to taking too long on the earlier steps).

Anyhow, when working with my wife on this problem, we’d reached the following impasse:

```scala
trait Handler[Operation[_]]:
  def apply[A](operation: Operation[A]): A
  def accepts(any: Any): Boolean

def run[Operation[_], A](dsl: DSL[A], handler: Handler[Operation[A]]): A =
  dsl match
    case ReadLine()         => StdIn.readLine()
    case PrintLine(message) => println(message)

    case Embed(operation) =>
      if handler.accepts(operation) then handler(operation.asInstanceOf[Operation[A]])
      else ???

    case Succeed(value) => value

    case FlatMap(dslX, f) =>
      val x = f(run(dslX, handlers*))
      run(x, handlers*)
```

Instead of simply launching headlong into the solution, I first tried to clarify the issue, saying something like: "The issue here is that this particular `handler` may not be able to handle the embedded operation. So, what can we do if our handler cannot handle this? How can we ever get the final `A` out?”.

In posing this question, it really hit me how non-incremental of a change this would need to be. Yes, we certainly *cannot* return an `A`, so this must still return a `DSL[A]`, until we've handled everything—cue our type-level tricks for tracking effects as intersection types. And then of course, we need to deal with creating a new continuation.

It then struck me then that there’s another, much simpler solution to the question: *"What can we do if our handler cannot handle this?”.* The obvious, incremental solution, which allows us to *actually* return an `A` right here in this method, is to ensure that we could indeed handle everything and anything that is thrown at us.

And how could we do that? Well, we simply gather up all of the handlers *before* we ever try to handle everything.

```scala
def run[A](dsl: DSL[A], handlers: Handler[?]*): A =
  dsl match
    case ReadLine()         => StdIn.readLine()
    case PrintLine(message) => println(message)

    case Embed(operation) =>
      val handler = handlers.find(_.accepts(operation)).get // <- Imagine a more clever optimization here.
      handler(operation.asInstanceOf)

    case Succeed(value) => value
    case FlatMap(dslX, f) =>
      val x = f(run(dslX, handlers*))
      run(x, handlers*)
```

Obviously, this doesn’t yet handle all of the features of real handlers, but I’m *pretty sure* it could (though I might be very wrong and could be publicly face-planting here 😅). This would also change Kyo’s semantics, as *no* progress will be made until all handlers are provided. However, I think that's practically what happens in most cases with the current model anyway.

The big upside would be *far fewer continuation **allocations***—drink! 🥃🥴—and a simplified handle/run method.

If this seems at all interesting, I’d be happy to explore it further. But I first wanted to write it up and get some thoughts from the gang (@fwbrasil, @hearnadam, @jiveshungerford, any other lurkers ), just in case I’ve gone mad or stupid.

**Comment by fwbrasil** [comment]
> As I was falling asleep last night, my mind wandered again—oh, the curse of programming—to implementing algebraic effect systems. When I worked on my little talk, I had a few extemporaneous practice sessions with my wife. I was trying to see just how incrementally I could make the refactoring from a basic free monad to a fully-powered, ad hoc effect handler implementation.

It seems the core redesign bug bit us both this weekend! 😆 The discussion in https://github.com/getkyo/kyo/pull/452 motivated me to work on a new encoding as well (more at the end). Can you believe that it's been almost 3 months since we completely redesigned the library's core? I agree it's time for some fun in another round!

> This leads to the bit which I had the most trouble decomposing pedagogically: The necessity of the continuation which continues the current handler loop only after some other, heretofore unknown, handler clears the unaccepted operation blocking the path ahead.

Yeah, this was a tough one to crack in the initial designs :) The current core essentially suspends the effect handling itself when another effect is pending. I think you could do something similar in the encoding you worked on.

> Obviously, this doesn’t yet handle all of the features of real handlers, but I’m pretty sure it could (though I might be very wrong and could be publicly face-planting here 😅). This would also change Kyo’s semantics, as no progress will be made until all handlers are provided. However, I think that's practically what happens in most cases with the current model anyway.

If we were able to do that, I think some things would become simpler. For example, if we always have all values when handling `Envs`, it should be possible to accept the effect in `Fibers.init`. 

The specific impl you shared would have a prohibitive performance cost, though. It behaves as an interpreter like in other effect systems, which wouldn't benefit of monomorphization of the execution but it doesn't seem a inherent limitation of the idea. Maybe we could try the new context functions for that? Something like:

```
opaque type <[+T, -S] = Runtime[S] ?=> T | Kyo[T, S]
```

Now about my new exploration, the discussion in https://github.com/getkyo/kyo/pull/452 got me thinking: would it be possible to enable arbitrary nesting for any Kyo computation? Although I do believe that composable effects preclude the need for nesting, allowing nesting would knock down one of the main criticisms of the library and avoid the complexity of the `Flat` check.

It seems making `<` an `AnyVal` provides exactly what would be needed: if the computation has the specific type, the compiler can avoid the boxing, but, once it gets passed to a generic scope, the compiler automatically introduces nesting. With this approach, we'd only pay the price of the `<` allocation only when necessary and the JIT should still be able to avoid a significant portion these allocations.

I'm also exploring a few other changes, including a major change in effect handling. It's WIP because the compiler is giving me a compilation error for the new `Transform` class when there's nesting but it's already functional: https://gist.github.com/fwbrasil/ed5aae2cd4520b648acdb5d8f55d8ab0

**Comment by fwbrasil** [comment]
I've explored a bit more and the approach with `AnyVal` for the pending type seems to be working properly with nesting! Updated gist: https://gist.github.com/fwbrasil/e6a8ca26fe998e79c3c436bb7a881f04

I also added the new core to `kyo-bench` and [implemented two benchmarks](https://github.com/getkyo/kyo/compare/main...new-core-initial-bench) with it. Performance is [even better](https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/ff71326bc11ebd8d33da474f8f122d70/raw/20cc32d11186bf205b2c97ba6c7acb6fc1f34ba1/jmh-result.json)! 🤯

![image](https://github.com/getkyo/kyo/assets/831175/80ef8aaf-a858-40a5-9e76-97133ea5a964)

**Comment by fwbrasil** [comment]
Woohoo! 🥳 I've found an encoding that doesn't use Command[Any], and effect handling is fully type-safe even with multiple types of operations like in `Var` 😻 https://gist.github.com/fwbrasil/a74b7998653fb836f6c4c770b299aebd

**Comment by fwbrasil** [comment]
New iteration supporting variance in effects like `Env` and `Abort`: https://gist.github.com/fwbrasil/18307aaeb5725e94f64d1e28a6ca34d2

**Comment by fwbrasil** [comment]
Last experimentation iteration adding back optimizations, safepoints, and wiring of local values: https://gist.github.com/fwbrasil/4ead88e77e5b9b380effbb5d27663f3a

I've also added comments with more background on the inlining decisions. I'll starting working on incorporating this new core into the code base.

**Comment by fwbrasil** [comment]
I've been working on updating the codebase with the new core but I'm not happy with the design making `<` extend `AnyVal`. It's easy to trigger boxing in unexpected places and the compiler has some limitations on where `AnyVal` types can be used. For example, extending generic interfaces with an `AnyVal` type parameter generates compile-time errors.

So what did I do? Explored yet a new design!!! 😂 I played with the idea of introducing a `Runtime` via context functions as mentioned previously here and was surprised by the result: it has essentially the same behavior as `AnyVal` to support nesting of computations but it has a much more predictable behavior for when boxing happens! The compiler desugars context functions in most scenarios as a method parameter, which avoids boxing, but, when nesting happens, it boxes the `<` type as a lambda. In this new design, the `<` type is defined as:

```scala
type <[+T, -S] = Runtime ?=> Kyo[T, S]

opaque type Kyo[+T, -S] = T | Pending[T, S]
```

In addition to this new encoding, I've added a few new features:

1. Since the `Runtime` is now available in all computations, I've decided to reuse it to introduce a mechanism to provide stack-safe execution for any Kyo computation (yes, you read that right!).
2. Kyo's current core has no way to introduce suspensions since it has no built-in effect. For example, `Locals` depends on `IOs` just to leverage its suspensions. This new design adds the `Defer` effect in the core itself, which enables using locals with `T < Any` computations. The effect is also used for the stack safety mechanism.
3.  Given that a `T < Any` can now be a suspended computation, `pure` is renamed to `eval`. It still evaluates only pure computations without any pending effects (besides the internal `Defer` effect).

I've done some initial performance testing with `BroadFlatMapBench` and `MtlBench`. The performance seems in the same ballpark as the current core but with a relatively small regression, which seems reasonable given the additional features.

Link to the gist: https://gist.github.com/fwbrasil/5a3601deabcb758a1e80c22aaa537557

@kitlangton this new encoding might enable the idea to suspend effect handling!

**Comment by fwbrasil** [comment]
I've added new `handler.dispatch` methods to avoid the custom handling loops in [`IOTask`](https://github.com/getkyo/kyo/blob/a5f0a4f3da6c03e3cb8588b1d147e0b23e7ce2b5/kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala#L43) and [`ZIOs`](https://github.com/getkyo/kyo/blob/a5f0a4f3da6c03e3cb8588b1d147e0b23e7ce2b5/kyo-zio/shared/src/main/scala/kyo/zios.scala#L26). The API is a bit clunky but still fully type-safe. I believe with that, we can avoid internal core classes in all effects. Example use:

```scala
object dispatchExample extends App:

    def program: String < (Var[Int] & Env[String] & IO) =
        for
            _ <- IO(println("Starting the program..."))
            _ <- Var.set(42)
            x <- Var.get[Int]
            _ <- IO(println(s"The value of Var is: $x"))
            _ <- Var.update[Int](_ + 10)
            y <- Var.get[Int]
            _ <- IO(println(s"Update ignored by handler: $y"))
            e <- Env.get[String]
            _ <- IO(println(s"The environment value is: $e"))
        yield "Done!"

    // This is still fully type safe 🤯
    def runProgram2: String < IO =
        handle.dispatch(Tag[Var[Int]], Tag[Env[String]], program)(
            [C] =>
                (input, cont) =>
                    input match
                        case Var.Input.Get()     => cont(42)
                        case Var.Input.Set(_)    => cont(())
                        case Var.Input.Update(_) => cont(()),
            [C] => (_, cont) => cont("Handling two effects at once!")
        )
    println(IO.run(runProgram2).eval)

    def runProgram3: String < Any =
        handle.dispatch(Tag[Var[Int]], Tag[Env[String]], Tag[IO], program)(
            [C] =>
                (input, cont) =>
                    input match
                        case Var.Input.Get()     => cont(42)
                        case Var.Input.Set(_)    => cont(())
                        case Var.Input.Update(_) => cont(()),
            [C] => (_, cont) => cont("Handling three effects at once!"),
            [C] => (_, cont) => cont(())
        )
    println(runProgram3.eval)

end dispatchExample
```

I still have to add safepoints to `Runtime` but this new design seems ok to proceed after that. Updated gist:
https://gist.github.com/fwbrasil/1b10e3c25b7702146f1adf5bf38eb964

**Comment by fwbrasil** [comment]
@kitlangton I'm closing this ticket for now since the new design has landed. I still think your idea to propagate handlers in a more efficient way is worth exploring, though! This [talk/paper](https://www.college-de-france.fr/fr/agenda/seminaire/structures-de-controle-de-goto-aux-effets-algebriques/design-and-compilation-of-efficient-effect-handlers-in-the-koka-language) by the Koka developers describes how it separates the resolution of handlers from the effect handling execution. It seems we could use something similar. Their "yield" bubbling technique is also quite similar to how Kyo accumulates transformations to provide the continuation.
