### ISSUE TITLE
Long serialization for String Tag

### ISSUE THREAD

**Issue by sideeffffect** [getkyo/kyo#930]
It seems like the Tag for `String` is rather long:
```
!X4;C%java.lang.constant.ConstantDesc;@=java.lang.constant.Constable;!7l;!8m;!9n;!T0;!U1;!V2;
```
https://scastie.scala-lang.org/uH7BvmmTQ2CnvAeji4g94A

Is that intentional? I would guess that Tags for `String`s are expected to be common and thus should be short.

**Comment by hearnadam** [comment]
The Tag needs to be long to support subtype checking. In fact, I am working on an optimization to include intersection/union support via a single string, instead of a collection of strings as implemented currently, which will increase the length. Since `Tag` is an opaque type, the `toString` will just show the raw string. You can use `.show` for a prettified version.

Strings are interned by the JVM, so these should not impact dynamically allocated memory.

**Comment by sideeffffect** [comment]
Fair enough, I was just a little surprised and curious. Feel free to close this ticket right away :)
